### ISSUE TITLE
Vundle install does not work

### ISSUE THREAD

**Issue by stabenfeldt** [mohitleo9/vim-fidget#10]
I added  `Bundle 'mohitleo9/vim-fidget'` to `.vimrc.bundles` and ran `BundleInstall`, but no vim-fidget is installed.  I get no error messages either. I have plenty of other vim-plugins already installed with Vundle, but this would not install. Any tips?

**Comment by stabenfeldt** [comment]
I managed to get it installed by `cd ~/.vim/bundle && git clone git://github.com/mohitleo9/vim-fidget.git && cd vim-fidget && npm install -g`
Copied from http://www.reddit.com/r/vim/comments/2ep6l3/jsfiddle_in_vim_with_live_update_and_can_share_at/

**Comment by mohitleo9** [comment]
That's exactly the way to do it.
Closing this.

**Comment by stabenfeldt** [comment]
Perhaps also remove the Vundle part from the README also,  if that doesn't work?

**Comment by stabenfeldt** [comment]
Update the install instructions to some that work, perhaps?
